### ISSUE TITLE
nice,work but i getting a training time error

### ISSUE THREAD

**Issue by poojapbabar** [JosephKJ/OWOD#102]
/Desktop/ORE/OWOD-master$ python tools/train_net.py --num-gpus 4 --config-file ./configs/PascalVOC-Detection/iOD/ft_19_p_1.yaml SOLVER.IMS_PER_BATCH 8 SOLVER.BASE_LR 0.005
Command Line Args: Namespace(config_file='./configs/PascalVOC-Detection/iOD/ft_19_p_1.yaml', resume=False, eval_only=False, num_gpus=4, num_machines=1, machine_rank=0, dist_url='tcp://127.0.0.1:50152', opts=['SOLVER.IMS_PER_BATCH', '8', 'SOLVER.BASE_LR', '0.005'])
Traceback (most recent call last):
  File "/home/sg/Desktop/ORE/OWOD-master/tools/train_net.py", line 163, in <module>
    launch(
  File "/home/sg/sdp_tf1_attention/cd/envs/ORE/lib/python3.10/site-packages/detectron2/engine/launch.py", line 67, in launch
    mp.spawn(
  File "/home/sg/sdp_tf1_attention/cd/envs/ORE/lib/python3.10/site-packages/torch/multiprocessing/spawn.py", line 240, in spawn
    return start_processes(fn, args, nprocs, join, daemon, start_method='spawn')
  File "/home/sg/sdp_tf1_attention/cd/envs/ORE/lib/python3.10/site-packages/torch/multiprocessing/spawn.py", line 198, in start_processes
    while not context.join():
  File "/home/sg/sdp_tf1_attention/cd/envs/ORE/lib/python3.10/site-packages/torch/multiprocessing/spawn.py", line 160, in join
    raise ProcessRaisedException(msg, error_index, failed_process.pid)
torch.multiprocessing.spawn.ProcessRaisedException: 

-- Process 1 terminated with the following error:
Traceback (most recent call last):
  File "/home/sg/sdp_tf1_attention/cd/envs/ORE/lib/python3.10/site-packages/torch/multiprocessing/spawn.py", line 69, in _wrap
    fn(i, *args)
  File "/home/sg/sdp_tf1_attention/cd/envs/ORE/lib/python3.10/site-packages/detectron2/engine/launch.py", line 95, in _distributed_worker
    assert torch.cuda.is_available(), "cuda is not available. Please check your installation."
AssertionError: cuda is not available. Please check your installation.

**Comment by JosephKJ** [comment]
Kindly check your CUDA installation and en environment configuration.
