### ISSUE TITLE
Error in running train_net.py file

### ISSUE THREAD

**Issue by GargShreeya** [JosephKJ/OWOD#136]
Command Line Args: Namespace(config_file='/content/OWOD/configs/OWOD/t1/t1_train.yaml', resume=True, eval_only=False, num_gpus=1, num_machines=1, machine_rank=0, dist_url='tcp://127.0.0.1:52125', opts=['SOLVER.IMS_PER_BATCH', '8', 'SOLVER.BASE_LR', '0.01', 'OUTPUT_DIR', './output/t1'])
Traceback (most recent call last):
  File "/content/OWOD/tools/train_net.py", line 163, in <module>
    launch(
  File "/content/detectron2/detectron2/engine/launch.py", line 84, in launch
    main_func(*args)
  File "/content/OWOD/tools/train_net.py", line 132, in main
    cfg = setup(args)
  File "/content/OWOD/tools/train_net.py", line 124, in setup
    cfg.merge_from_file(args.config_file)
  File "/content/detectron2/detectron2/config/config.py", line 69, in merge_from_file
    self.merge_from_other_cfg(loaded_cfg)
  File "/usr/local/lib/python3.10/dist-packages/fvcore/common/config.py", line 132, in merge_from_other_cfg
    return super().merge_from_other_cfg(cfg_other)
  File "/usr/local/lib/python3.10/dist-packages/yacs/config.py", line 217, in merge_from_other_cfg
    _merge_a_into_b(cfg_other, self, self, [])
  File "/usr/local/lib/python3.10/dist-packages/yacs/config.py", line 491, in _merge_a_into_b
    raise KeyError("Non-existent config key: {}".format(full_key))
KeyError: 'Non-existent config key: OWOD'

I am getting this error please solve this error

**Comment by 1928908522** [comment]
you ought install "OWOD" in dir "./OWOD"
