### ISSUE TITLE
KeyError: 'Non-existent config key: OWOD'

### ISSUE THREAD

**Issue by fuchao01** [JosephKJ/OWOD#21]
HI,
I use the provided docker and report the following error, how can I solve it?

Command Line Args: Namespace(config_file='./configs/OWOD/iOD/all_20_train.yaml', dist_url='tcp://127.0.0.1:50177', eval_only=False, machine_rank=0, num_gpus=1, num_machines=1, opts=[], resume=False)
Traceback (most recent call last):
  File "tools/train_net.py", line 169, in <module>
    args=(args,),
  File "/home/appuser/detectron2_repo/detectron2/engine/launch.py", line 62, in launch
    main_func(*args)
  File "tools/train_net.py", line 132, in main
    cfg = setup(args)
  File "tools/train_net.py", line 124, in setup
    cfg.merge_from_file(args.config_file)
  File "/home/appuser/detectron2_repo/detectron2/config/config.py", line 54, in merge_from_file
    self.merge_from_other_cfg(loaded_cfg)
  File "/home/appuser/.local/lib/python3.6/site-packages/fvcore/common/config.py", line 123, in merge_from_other_cfg
    return super().merge_from_other_cfg(cfg_other)
  File "/home/appuser/.local/lib/python3.6/site-packages/yacs/config.py", line 217, in merge_from_other_cfg
    _merge_a_into_b(cfg_other, self, self, [])
  File "/home/appuser/.local/lib/python3.6/site-packages/yacs/config.py", line 491, in _merge_a_into_b
    raise KeyError("Non-existent config key: {}".format(full_key))
KeyError: 'Non-existent config key: OWOD'

**Comment by AshishRMenon** [comment]
Kindly check issue #10

**Comment by JosephKJ** [comment]
Thank you @AshishRMenon. @fuchao01: Hope you could resolve the issue!
