### ISSUE TITLE
How can I test a single image?

### ISSUE THREAD

**Issue by LLsmile** [JosephKJ/OWOD#57]
For OWOD, I think it should be common to test any image in the real world. So I want to test a single image taken from my camera. But the guide in the code base seems too complicated. Is there any simple way to test a image, such as python main.py model.py test.jpg?

**Comment by feifeiwei** [comment]
look at the script visualise_detections.py @LLsmile

**Comment by LLsmile** [comment]
@feifeiwei Thanks for your help. But it seems there are still some error in my code. 
appuser@855ef1fd2347:/OWOD$ python visualise_detections.py 
Failed to load OpenCL runtime
Traceback (most recent call last):
  File "visualise_detections.py", line 11, in <module>
    from detectron2.engine import DefaultPredictor
  File "/OWOD/detectron2/engine/__init__.py", line 4, in <module>
    from .train_loop import *
  File "/OWOD/detectron2/engine/train_loop.py", line 12, in <module>
    from reliability.Fitters import Fit_Weibull_3P
ModuleNotFoundError: No module named 'reliability'

**Comment by ztfmars** [comment]
> For OWOD, I think it should be common to test any image in the real world. So I want to test a single image taken from my camera. But the guide in the code base seems too complicated. Is there any simple way to test a image, such as python main.py model.py test.jpg?
----------------------------------------------------------------------------------------
**detectron2, yyds~~~~**

have a try, wish it will be helpful to u....
`cd demo`
`python demo.py --config-file ../configs/OWOD/t1/t1_test.yaml --video-input /home/xxxx/shanghai.mp4 --opt MODEL.WEIGHTS /home/xxxx/t1/model_final.pth`


`camera, image, video` , either of them is ok, 
if u don't know how to set the parameters,  try like this:

`python demo.py --help`


**or set parameters as followings:**
usage: demo.py [-h] [--config-file FILE] [--webcam]
               [--video-input VIDEO_INPUT] [--input INPUT [INPUT ...]]
               [--output OUTPUT] [--confidence-threshold CONFIDENCE_THRESHOLD]
               [--opts ...]

Detectron2 demo for builtin configs

optional arguments:
  -h, --help            show this help message and exit
  --config-file FILE    path to config file
  --webcam              Take inputs from webcam.
  --video-input VIDEO_INPUT
                        Path to video file.
  --input INPUT [INPUT ...]
                        A list of space separated input images; or a single
                        glob pattern such as 'directory/*.jpg'
  --output OUTPUT       A file or directory to save output visualizations. If
                        not given, will show output in an OpenCV window.
  --confidence-threshold CONFIDENCE_THRESHOLD
                        Minimum score for instance predictions to be shown
  --opts ...            Modify config options using the command-line 'KEY
                        VALUE' pairs

**Comment by JiuqingDong** [comment]
> @feifeiwei Thanks for your help. But it seems there are still some error in my code. When I use the detectrons folder in code base, the error shows like this: appuser@855ef1fd2347:/OWOD$ python visualise_detections.py Failed to load OpenCL runtime Traceback (most recent call last): File "visualise_detections.py", line 11, in from detectron2.engine import DefaultPredictor File "/OWOD/detectron2/engine/**init**.py", line 4, in from .train_loop import * File "/OWOD/detectron2/engine/train_loop.py", line 12, in from reliability.Fitters import Fit_Weibull_3P ModuleNotFoundError: No module named 'reliability'
> 
> And when I remove the detectron2 folder and use the detection2 from official installation, the error shows like this: python visualise_detections.py Traceback (most recent call last): File "visualise_detections.py", line 64, in cfg.merge_from_file(cfg_file) File "/home/liaolin/.local/lib/python3.6/site-packages/detectron2/config/config.py", line 69, in merge_from_file self.merge_from_other_cfg(loaded_cfg) File "/home/liaolin/.local/lib/python3.6/site-packages/fvcore/common/config.py", line 123, in merge_from_other_cfg return super().merge_from_other_cfg(cfg_other) File "/home/liaolin/.local/lib/python3.6/site-packages/yacs/config.py", line 217, in merge_from_other_cfg _merge_a_into_b(cfg_other, self, self, []) File "/home/liaolin/.local/lib/python3.6/site-packages/yacs/config.py", line 491, in _merge_a_into_b raise KeyError("Non-existent config key: {}".format(full_key)) KeyError: 'Non-existent config key: OWOD'

Did you solve this problem? I also got this issue: ModuleNotFoundError: No module named 'reliability'

**Comment by YH-2023** [comment]
> @feifeiwei Thanks for your help. But it seems there are still some error in my code. 感谢您的帮助。但我的代码似乎仍然存在一些错误。 When I use the detectrons folder in code base, the error shows like this: 当我在代码库中使用 detectorrons 文件夹时，错误显示如下： appuser@855ef1fd2347:/OWOD$ python visualise_detections.py Failed to load OpenCL runtime 无法加载 OpenCL 运行时 Traceback (most recent call last):回溯（最近一次调用最后一次）： File "visualise_detections.py", line 11, in 文件“visualise_detections.py”，第 11 行，位于 from detectron2.engine import DefaultPredictor 从 detectorron2.engine 导入 DefaultPredictor File "/OWOD/detectron2/engine/**init**.py", line 4, in 文件“/OWOD/Detectron2/engine/init.py”，第 4 行，位于 from .train_loop import * 从.train_loop导入* File "/OWOD/detectron2/engine/train_loop.py", line 12, in 文件“/OWOD/Detectron2/engine/train_loop.py”，第 12 行，位于 from reliability.Fitters import Fit_Weibull_3P 从可靠性.Fitters导入Fit_Weibull_3P ModuleNotFoundError: No module named 'reliability'ModuleNotFoundError：没有名为“可靠性”的模块
> 
> And when I remove the detectron2 folder and use the detection2 from official installation, the error shows like this:当我删除 detectorron2 文件夹并使用官方安装中的 detector2 时，错误显示如下： python visualise_detections.py python 可视化检测.py Traceback (most recent call last):回溯（最近一次调用最后一次）： File "visualise_detections.py", line 64, in 文件“visualise_detections.py”，第 64 行，位于 cfg.merge_from_file(cfg_file) File "/home/liaolin/.local/lib/python3.6/site-packages/detectron2/config/config.py", line 69, in merge_from_file 文件“/home/liaolin/.local/lib/python3.6/site-packages/detectron2/config/config.py”，第 69 行，在 merge_from_file 中 self.merge_from_other_cfg(loaded_cfg) File "/home/liaolin/.local/lib/python3.6/site-packages/fvcore/common/config.py", line 123, in merge_from_other_cfg 文件“/home/liaolin/.local/lib/python3.6/site-packages/fvcore/common/config.py”，第 123 行，位于 merge_from_other_cfg 中 return super().merge_from_other_cfg(cfg_other) 返回 super().merge_from_other_cfg(cfg_other) File "/home/liaolin/.local/lib/python3.6/site-packages/yacs/config.py", line 217, in merge_from_other_cfg 文件“/home/liaolin/.local/lib/python3.6/site-packages/yacs/config.py”，第 217 行，merge_from_other_cfg _merge_a_into_b(cfg_other, self, self, []) _merge_a_into_b(cfg_other, 自我, 自我, []) File "/home/liaolin/.local/lib/python3.6/site-packages/yacs/config.py", line 491, in _merge_a_into_b 文件“/home/liaolin/.local/lib/python3.6/site-packages/yacs/config.py”，第 491 行，在 _merge_a_into_b 中 raise KeyError("Non-existent config key: {}".format(full_key))raise KeyError("不存在的配置密钥：{}".format(full_key)) KeyError: 'Non-existent config key: OWOD'KeyError：“不存在的配置密钥：OWOD”

How did you solve this problem?
